-- Group Number: Group 37
-- Group Members: Wong Jiung Ming, Diong Chen Xi, Leong Yen Ni

-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-27 11:39:35 SGT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on

SPOOL wc_schema_output.txt


DROP TABLE address CASCADE CONSTRAINTS;

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE cruise CASCADE CONSTRAINTS;

DROP TABLE cruise_port CASCADE CONSTRAINTS;

DROP TABLE manifest CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE participant CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE port_temperature CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE address (
    address_id       NUMBER(10) NOT NULL,
    address_street   VARCHAR2(50) NOT NULL,
    address_town     VARCHAR2(50) NOT NULL,
    address_postcode VARCHAR2(10) NOT NULL,
    address_country  VARCHAR2(2) NOT NULL
);

COMMENT ON COLUMN address.address_street IS
    'Address street';

COMMENT ON COLUMN address.address_town IS
    'Address town';

COMMENT ON COLUMN address.address_postcode IS
    'Address post code';

COMMENT ON COLUMN address.address_country IS
    'address country';

ALTER TABLE address ADD CONSTRAINT address_pk PRIMARY KEY ( address_id );

CREATE TABLE cabin (
    ship_code      NUMBER(10) NOT NULL,
    cabin_number   VARCHAR2(5) NOT NULL,
    cabin_capacity NUMBER(5) NOT NULL,
    cabin_class    VARCHAR2(50) NOT NULL
);

ALTER TABLE cabin
    ADD CHECK ( cabin_class IN ( 'balcony', 'interior', 'ocean view', 'suite' ) );

COMMENT ON COLUMN cabin.ship_code IS
    'ship_code';

COMMENT ON COLUMN cabin.cabin_number IS
    'Cabin number.';

COMMENT ON COLUMN cabin.cabin_capacity IS
    'Cabin capacity.';

COMMENT ON COLUMN cabin.cabin_class IS
    'Cabin class.';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cabin_number,
                                                        ship_code );

ALTER TABLE cabin ADD CONSTRAINT cabin_ship_sk UNIQUE ( cabin_number );

CREATE TABLE country (
    port_country_code VARCHAR2(2) NOT NULL,
    country_name      VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN country.port_country_code IS
    'country code';

COMMENT ON COLUMN country.country_name IS
    'country name';

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( port_country_code );

CREATE TABLE cruise (
    cruise_id   NUMBER(4) NOT NULL,
    cruise_name VARCHAR2(50) NOT NULL,
    cruise_desc VARCHAR2(50) NOT NULL,
    ship_code   NUMBER(10) NOT NULL
);

COMMENT ON COLUMN cruise.cruise_id IS
    'cruise''s id';

COMMENT ON COLUMN cruise.cruise_name IS
    'cruise''s name';

COMMENT ON COLUMN cruise.cruise_desc IS
    'cruise''s description';

COMMENT ON COLUMN cruise.ship_code IS
    'ship_code';

ALTER TABLE cruise ADD CONSTRAINT cruise_pk PRIMARY KEY ( cruise_id );

CREATE TABLE cruise_port (
    cruise_id   NUMBER(4) NOT NULL,
    cp_datetime DATE NOT NULL,
    cp_status   VARCHAR2(10) NOT NULL,
    port_code   VARCHAR2(5) NOT NULL
);

COMMENT ON COLUMN cruise_port.cruise_id IS
    'cruise''s id';

COMMENT ON COLUMN cruise_port.cp_datetime IS
    'arrival or departure time  of a cruise in a certain port';

COMMENT ON COLUMN cruise_port.cp_status IS
    'status of datetime (arrival/departure)';

COMMENT ON COLUMN cruise_port.port_code IS
    'Port code';

ALTER TABLE cruise_port ADD CONSTRAINT cruise_port_pk PRIMARY KEY ( cruise_id,
                                                                    cp_datetime );

CREATE TABLE manifest (
    cruise_id                 NUMBER(4) NOT NULL,
    passenger_id              NUMBER(5) NOT NULL,
    manifest_psger_fbdatetime DATE NOT NULL,
    cabin_number              VARCHAR2(5) NOT NULL,
    ship_code                 NUMBER(10) NOT NULL
);

COMMENT ON COLUMN manifest.cruise_id IS
    'cruise''s id';

COMMENT ON COLUMN manifest.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN manifest.manifest_psger_fbdatetime IS
    'First boarding date and time of passenger';

COMMENT ON COLUMN manifest.cabin_number IS
    'Cabin number.';

COMMENT ON COLUMN manifest.ship_code IS
    'ship_code';

ALTER TABLE manifest ADD CONSTRAINT manifest_pk PRIMARY KEY ( cruise_id,
                                                              passenger_id );

CREATE TABLE operator (
    operator_id           NUMBER(10) NOT NULL,
    operator_company_name VARCHAR2(50) NOT NULL,
    operator_ceo_name     VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN operator.operator_id IS
    'Operator''s ID number.';

COMMENT ON COLUMN operator.operator_company_name IS
    'Operator''s Company Name.';

COMMENT ON COLUMN operator.operator_ceo_name IS
    'Operator''s CEO name.';

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( operator_id );

CREATE TABLE participant (
    port_code        VARCHAR2(5) NOT NULL,
    tour_number      NUMBER(3) NOT NULL,
    passenger_id     NUMBER(5) NOT NULL,
    payment_received VARCHAR2(3) NOT NULL
);

ALTER TABLE participant
    ADD CHECK ( payment_received IN ( 'no', 'yes' ) );

COMMENT ON COLUMN participant.port_code IS
    'Port code';

COMMENT ON COLUMN participant.tour_number IS
    'tour number';

COMMENT ON COLUMN participant.passenger_id IS
    'passenger''s id';

COMMENT ON COLUMN participant.payment_received IS
    'Whether or not the payment of a port''s tour of a certain passenger is received';

ALTER TABLE participant
    ADD CONSTRAINT participant_pk PRIMARY KEY ( tour_number,
                                                passenger_id,
                                                port_code );

CREATE TABLE passenger (
    passenger_id          NUMBER(5) NOT NULL,
    passenger_fname       VARCHAR2(50) NOT NULL,
    passenger_lname       VARCHAR2(50) NOT NULL,
    passenger_gender      VARCHAR2(1) NOT NULL,
    passenger_dob         DATE NOT NULL,
    passenger_guardian_id NUMBER(10),
    address_id            NUMBER(10) NOT NULL
);

ALTER TABLE passenger
    ADD CHECK ( passenger_gender IN ( 'O ', 'F', 'M' ) );

COMMENT ON COLUMN passenger.passenger_id IS
    'Passenger ID';

COMMENT ON COLUMN passenger.passenger_fname IS
    'Passenger first name';

COMMENT ON COLUMN passenger.passenger_lname IS
    'Passenger last name';

COMMENT ON COLUMN passenger.passenger_gender IS
    'Passenger gender';

COMMENT ON COLUMN passenger.passenger_dob IS
    'Passenger''s date of birth';

COMMENT ON COLUMN passenger.passenger_guardian_id IS
    'Passenger ID';

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( passenger_id );

CREATE TABLE port (
    port_code         VARCHAR2(5) NOT NULL,
    port_name         VARCHAR2(50) NOT NULL,
    port_population   NUMBER(5) NOT NULL,
    port_longitude    NUMBER(10, 7) NOT NULL,
    port_latitude     NUMBER(9, 7),
    port_country_code VARCHAR2(2) NOT NULL
);

COMMENT ON COLUMN port.port_code IS
    'Port code';

COMMENT ON COLUMN port.port_name IS
    'port name';

COMMENT ON COLUMN port.port_population IS
    'port population';

COMMENT ON COLUMN port.port_longitude IS
    'port longitude';

COMMENT ON COLUMN port.port_latitude IS
    'port latitude';

COMMENT ON COLUMN port.port_country_code IS
    'country code';

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_code );

CREATE TABLE port_temperature (
    port_code                 VARCHAR2(5) NOT NULL,
    port_temperature_month    DATE NOT NULL,
    port_temperature_avg_high NUMBER(2),
    port_temperature_avg_low  NUMBER(2)
);

COMMENT ON COLUMN port_temperature.port_code IS
    'Port code';

COMMENT ON COLUMN port_temperature.port_temperature_month IS
    'The month recorded of a port''s temperature';

COMMENT ON COLUMN port_temperature.port_temperature_avg_high IS
    'The average high temperature of a port in a certain month';

COMMENT ON COLUMN port_temperature.port_temperature_avg_low IS
    'The average low temperature of a port in a certain month';

ALTER TABLE port_temperature ADD CONSTRAINT port_temperature_pk PRIMARY KEY ( port_temperature_month,
                                                                              port_code );

CREATE TABLE ship (
    ship_code               NUMBER(10) NOT NULL,
    ship_name               VARCHAR2(50) NOT NULL,
    ship_commission_date    DATE NOT NULL,
    ship_tonnage            NUMBER(5) NOT NULL,
    ship_max_capacity       NUMBER(5) NOT NULL,
    ship_registered_country VARCHAR2(50) NOT NULL,
    operator_id             NUMBER(10) NOT NULL
);

COMMENT ON COLUMN ship.ship_code IS
    'ship_code';

COMMENT ON COLUMN ship.ship_name IS
    'ship''s name';

COMMENT ON COLUMN ship.ship_commission_date IS
    'ships''s commission date';

COMMENT ON COLUMN ship.ship_tonnage IS
    'ship''s tonnage';

COMMENT ON COLUMN ship.ship_max_capacity IS
    'ship''s max guest capacity';

COMMENT ON COLUMN ship.ship_registered_country IS
    'ship''s registered country';

COMMENT ON COLUMN ship.operator_id IS
    'Operator''s ID number.';

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_code );

CREATE TABLE tour (
    port_code              VARCHAR2(5) NOT NULL,
    tour_number            NUMBER(3) NOT NULL,
    tour_name              VARCHAR2(50) NOT NULL,
    tour_date              DATE NOT NULL,
    tour_desc              VARCHAR2(50),
    tour_hrs_req           NUMBER(3, 1) NOT NULL,
    tour_cost_pp           NUMBER(5, 2) NOT NULL,
    tour_wheelchair_access VARCHAR2(3) NOT NULL,
    tour_availability      VARCHAR2(50) NOT NULL,
    tour_starttime         DATE NOT NULL
);

ALTER TABLE tour
    ADD CHECK ( tour_wheelchair_access IN ( 'no', 'yes' ) );

COMMENT ON COLUMN tour.port_code IS
    'Port code';

COMMENT ON COLUMN tour.tour_number IS
    'tour number';

COMMENT ON COLUMN tour.tour_name IS
    'tour name';

COMMENT ON COLUMN tour.tour_date IS
    'date of tour';

COMMENT ON COLUMN tour.tour_desc IS
    'tour description';

COMMENT ON COLUMN tour.tour_hrs_req IS
    'The time required for a tour';

COMMENT ON COLUMN tour.tour_cost_pp IS
    'tour cost per person';

COMMENT ON COLUMN tour.tour_wheelchair_access IS
    'Wheelchair access of a tour';

COMMENT ON COLUMN tour.tour_availability IS
    'Availability of a tour';

COMMENT ON COLUMN tour.tour_starttime IS
    'Starting time of a tour';

ALTER TABLE tour ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_number,
                                                      port_code );

ALTER TABLE manifest
    ADD CONSTRAINT cabin_manifest FOREIGN KEY ( cabin_number,
                                                ship_code )
        REFERENCES cabin ( cabin_number,
                           ship_code );

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_cruise_port FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE manifest
    ADD CONSTRAINT cruise_manifest FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE ship
    ADD CONSTRAINT operator_ship FOREIGN KEY ( operator_id )
        REFERENCES operator ( operator_id );

ALTER TABLE passenger
    ADD CONSTRAINT passenger_address FOREIGN KEY ( address_id )
        REFERENCES address ( address_id );

ALTER TABLE manifest
    ADD CONSTRAINT passenger_manifest FOREIGN KEY ( passenger_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE passenger
    ADD CONSTRAINT passenger_passenger FOREIGN KEY ( passenger_guardian_id )
        REFERENCES passenger ( passenger_id );

ALTER TABLE cruise_port
    ADD CONSTRAINT port_cruise_port FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE participant
    ADD CONSTRAINT port_participant FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE port_temperature
    ADD CONSTRAINT port_port_temperature FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE tour
    ADD CONSTRAINT port_tour FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE port
    ADD CONSTRAINT relation_12 FOREIGN KEY ( port_country_code )
        REFERENCES country ( port_country_code );

ALTER TABLE cabin
    ADD CONSTRAINT ship_cabin FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE cruise
    ADD CONSTRAINT ship_cruise FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

SPOOL off

set echo off

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            13
-- CREATE INDEX                             0
-- ALTER TABLE                             32
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
